#ifndef EXIT_RETURN_CODES_H_
#define EXIT_RETURN_CODES_H_
#include <errno.h>

enum ExitReturnCodes {
  JOB_SUCCESS = 0,
  JOB_ALREADY_COMPLETED = ENOTRECOVERABLE + 1,
  NO_JOBS,
  WRONG_JOB_TYPE, 
  FAILED_TO_LOAD_HAND,
  FAILED_TO_LOAD_VIRTUAL_CONTACTS,
  FAILED_TO_LOAD_OBJECT,
  FAILED_TO_LOAD_WORLD,
  NO_OBJECT_IN_WORLD,
  FAILED_TO_CONNECT_TO_DBASE,
  FAILED_TO_SAVE_GRASPS
};



#endif
